url: "https://newagemotors.co.zw" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "New Age Motors"
subtitle: "The future of motoring"
description: "A modern website for a new age"
author: "Tanaka Mawere"
email: "contact@newagemotors.co.zw"
phone: "+263 77 123 4567"
address: "1234 New Age Street, Harare, Zimbabwe"
social:
  twitter: "https://twitter.com/newagemotors"
  facebook: "https://facebook.com/newagemotors"
  instagram: "https://instagram.com/newagemotors"
  whatsapp: "https://wa.me/263771234567"